### ISSUE TITLE
Do you create a foldcraft launcher for Android 7.0

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [root-S7/FoldCraftLauncher#1]
### Description

Do you create a fold launcher for Android 7.0 please do it

### Why

Do it please

**Comment by root-S7** [comment]
so...
![image](https://github.com/root-S7/FoldCraftLauncher/assets/110681414/10c476fa-c75b-49fe-bb3d-2b0e198eda35)
Android O = 8.0

**Comment by kjjjjjjjjjjjj** [comment]
Do you see make me the hmcl pe for Android 7.0

**Comment by root-S7** [comment]
###
