### ISSUE TITLE
可以设置打包进apk的功能

### ISSUE THREAD

**Issue by hyplant** [root-S7/FoldCraftLauncher#28]
### Description

在apk的<code>assets</code>中添加一个文件夹，让其中的文件可以替换<code>/data/data/com.tungsten.fcl/</code>中的文件，以便对：
```
/data/data/com.tungsten.fcl/files/menu_setting.json
/data/data/com.tungsten.fcl/files/config.json
/data/data/com.tungsten.fcl/shared_prefs
```
等文件进行替换。

**Comment by root-S7** [comment]
后续所有设置会放到/assets/config.properties配置文件内，方便用户修改

**Comment by root-S7** [comment]
还有就是最近有事，没时间更新

**Comment by hyplant** [comment]
通过配置文件写入设置始终存在一定的局限性，版本更新后添加新的设置，配置文件也需要更新。如果未来版本中可更改的设置很多，配置文件就会很乱。
因此建议添加一个新的文件夹，让里面的文件可以覆盖`config.json`，覆盖完成后再把第三方登录服务器写入。同时`menu_setting.json`与其在同一目录中，也可以通过这种方法覆盖。

另外希望添加自定义默认主题的功能，更改主题和背景图片的默认值，即用户点击重置后会还原到整合包作者提供的主题和背景图片。

另外希望`assets/controllers`中的所有控制器配置和`input`以及`styles`文件都可以被识别，便于添加更多控制器配置、快捷输入内容。

**Comment by root-S7** [comment]
https://github.com/root-S7/FoldCraftLauncher/commit/2543c665f290c5f756983aa42f1354c74b762352
